name: NASA Project CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    env:
      CI: true # in continous integration enviroment, exit test automatically,
      MONGO_URL: mongodb://localhost/nasa
    strategy: # can run build job in diff env
      matrix:
        node-version: [20.x, 16.x]
        mongodb-version: ["7.0"]
    runs-on: ubuntu-latest #specify which platform this jobs should run on  [windows-latest,macos-latest]
    steps: #define actions, that is going to be taken on operating system when build job is triggerd by push,pull
      - name: Checkout code # Step 1: Checkout the repository to the runner
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}} # Specify the Node.js version you want to use
      - name: Use MongoDB from github actions
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install #Install dependencies defined in root package.json on specified operating system
      - run: npm run build --prefix client
      - run: npm test # default in client test in react app keep watching,reqiure exit manully, so we set CI: true ro exit auto
